plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '3.5.10'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.drawing'
version = '0.0.1-SNAPSHOT'
description = 'Teamproject for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // Spring Boot Starter
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    
    // Mybatis & Oracle
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.5'
    runtimeOnly 'com.oracle.database.jdbc:ojdbc11'
    
    // JSP & JSTL (태그 라이브러리 핵심)
    implementation 'org.apache.tomcat.embed:tomcat-embed-jasper'
    implementation 'org.apache.commons:commons-csv:1.10.0'
    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl'
    
    // Spring Security Taglibs (이게 있어야 sec: 태그 작동)
    implementation 'org.springframework.security:spring-security-taglibs'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    
    // DevTools & Test
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter-test:3.0.5'
    
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    
    // 
    implementation 'org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.1'
	implementation 'org.apache.httpcomponents:httpclient:4.5.13'
    
}

eclipse.wtp.facet {
	facet name: 'jst.web', version: '5.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
