spring.application.name=drawing
# JSP 설정 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
# Oracle 설정 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=scott
spring.datasource.password=tiger
# MyBatis 설정 
#mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/**.xml
# MyBatis null 처리 방식 지정 
mybatis.configuration.jdbc-type-for-null=VARCHAR
mybatis.type-aliases-package=com.drawing.springboot.dto
# 파일업로드 설정
# 최대 파일 크기 설정 (기본값 : 1MB)
spring.servlet.multipart.max-file-size = 10MB
# 최대 요청 크기 설정 (기본값 : 1MB)
spring.servlet.multipart.max-request-size = 10MB

# Spring Security OAuth2 설정
spring.security.oauth2.client.registration.kakao.client-id=cc71d2dce34b07aa23b9fe6d6432ad57
spring.security.oauth2.client.registration.kakao.client-secret=XymyZ31fwpLyzYgG0RUcmexMrJMUdZ7j
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname, account_email

# Kakao Provider 설정
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
